[hotkey]
key = "SCROLLLOCK"
modifiers = []

[audio]
device = "default"
sample_rate = 16000
max_duration_secs = 60

[output]
mode = "type"
shift_enter_newlines = true

  [output.notification]
  on_transcription = false
